<?xml version="1.0" encoding="UTF-8" ?>
<Package name="SolucionRegistro" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="BorrarCaras" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="index" src="html/index.html" />
        <File name="script" src="html/js/script.js" />
        <File name="bocetoLogoConversacion" src="html/imagenes/conversacion/bocetoLogoConversacion.png" />
        <File name="volverConversacion" src="html/imagenes/conversacion/volverConversacion.png" />
        <File name="backgroundCuadrados" src="html/imagenes/index/backgroundCuadrados.png" />
        <File name="bocetoLogoIndex" src="html/imagenes/index/bocetoLogoIndex.png" />
        <File name="cognitivas" src="html/imagenes/index/cognitivas.png" />
        <File name="conversacion" src="html/imagenes/index/conversacion.png" />
        <File name="emocionales" src="html/imagenes/index/emocionales.png" />
        <File name="entrenamiento" src="html/imagenes/index/entrenamiento.png" />
        <File name="fisicas" src="html/imagenes/index/fisicas.png" />
        <File name="google" src="html/imagenes/index/google.png" />
        <File name="youtube" src="html/imagenes/index/youtube.png" />
        <File name="bocetoLogoEntrenar" src="html/imagenes/entrenar/bocetoLogoEntrenar.png" />
        <File name="botonVolverEntrenar" src="html/imagenes/entrenar/botonVolverEntrenar.png" />
        <File name="cognitivas" src="html/imagenes/entrenar/cognitivas.png" />
        <File name="emocionales" src="html/imagenes/entrenar/emocionales.png" />
        <File name="fisicas" src="html/imagenes/entrenar/fisicas.png" />
        <File name="fondoCognitivo" src="html/imagenes/entrenar/fondoCognitivo.png" />
        <File name="fondoEmocional" src="html/imagenes/entrenar/fondoEmocional.png" />
        <File name="fondoFisicas" src="html/imagenes/entrenar/fondoFisicas.png" />
        <File name="textoCognitivasEntrenar" src="html/imagenes/entrenar/textoCognitivasEntrenar.png" />
        <File name="textoEmocionalesEntrenar" src="html/imagenes/entrenar/textoEmocionalesEntrenar.png" />
        <File name="textoEntrenar" src="html/imagenes/entrenar/textoEntrenar.png" />
        <File name="textoFisicasEntrenar" src="html/imagenes/entrenar/textoFisicasEntrenar.png" />
        <File name="textoVolverEntrenar" src="html/imagenes/entrenar/textoVolverEntrenar.png" />
        <File name="backgroundConversacion" src="html/imagenes/conversacion/backgroundConversacion.png" />
        <File name="bocetoLogoBuscador" src="html/imagenes/buscador/bocetoLogoBuscador.png" />
        <File name="botonVolverBuscador" src="html/imagenes/buscador/botonVolverBuscador.png" />
        <File name="textoVolverBuscador" src="html/imagenes/buscador/textoVolverBuscador.png" />
        <File name="mosaicoAzul" src="html/imagenes/parejas/mosaicoAzul.png" />
        <File name="mosaicoRojo" src="html/imagenes/parejas/mosaicoRojo.png" />
        <File name="mosaicoVerde" src="html/imagenes/parejas/mosaicoVerde.png" />
        <File name="interrogacionParejas" src="html/imagenes/parejas/interrogacionParejas.png" />
        <File name="mosaicoNaranja" src="html/imagenes/parejas/mosaicoNaranja.png" />
        <File name="begin_reco" src="audio/begin_reco.wav" />
        <File name="end_reco" src="audio/end_reco.wav" />
        <File name="background" src="html/imagenes/assistant/background.png" />
        <File name="loader" src="html/imagenes/assistant/loader.gif" />
        <File name="background-urola-grey" src="html/imagenes/conversacion/background-urola-grey.png" />
        <File name="pepper" src="html/imagenes/conversacion/pepper.png" />
        <File name="user" src="html/imagenes/conversacion/user.png" />
        <File name="loader-listening" src="html/imagenes/conversacion/loader-listening.gif" />
        <File name="loader-recognition" src="html/imagenes/conversacion/loader-recognition.gif" />
        <File name="background-urola-white" src="html/imagenes/conversacion/background-urola-white.png" />
        <File name="help" src="html/imagenes/conversacion/help.png" />
        <File name="alertify.core" src="html/css/alertify.core.css" />
        <File name="alertify.default" src="html/css/alertify.default.css" />
        <File name="botonVolverUser" src="html/imagenes/user/botonVolverUser.png" />
        <File name="cognitivas" src="html/imagenes/user/cognitivas.png" />
        <File name="emocionales" src="html/imagenes/user/emocionales.png" />
        <File name="fisicas" src="html/imagenes/user/fisicas.png" />
        <File name="fondoCognitivo" src="html/imagenes/user/fondoCognitivo.png" />
        <File name="fondoEmocional" src="html/imagenes/user/fondoEmocional.png" />
        <File name="fondoFisicas" src="html/imagenes/user/fondoFisicas.png" />
        <File name="no-profile" src="html/imagenes/user/no-profile.jpg" />
        <File name="textoCognitivasEntrenar" src="html/imagenes/user/textoCognitivasEntrenar.png" />
        <File name="textoEmocionalesEntrenar" src="html/imagenes/user/textoEmocionalesEntrenar.png" />
        <File name="textoEntrenar" src="html/imagenes/user/textoEntrenar.png" />
        <File name="textoFisicasEntrenar" src="html/imagenes/user/textoFisicasEntrenar.png" />
        <File name="textoVolverUser" src="html/imagenes/user/textoVolverUser.png" />
        <File name="user" src="html/css/user.css" />
        <File name="daterangepicker" src="html/vendor/datepicker/daterangepicker.css" />
        <File name="daterangepicker" src="html/vendor/datepicker/daterangepicker.js" />
        <File name="moment.min" src="html/vendor/datepicker/moment.min.js" />
        <File name="HELP-US-OUT" src="html/vendor/font-awesome-4.7/HELP-US-OUT.txt" />
        <File name="font-awesome" src="html/vendor/font-awesome-4.7/css/font-awesome.css" />
        <File name="font-awesome.min" src="html/vendor/font-awesome-4.7/css/font-awesome.min.css" />
        <File name="FontAwesome" src="html/vendor/font-awesome-4.7/fonts/FontAwesome.otf" />
        <File name="fontawesome-webfont" src="html/vendor/font-awesome-4.7/fonts/fontawesome-webfont.eot" />
        <File name="fontawesome-webfont" src="html/vendor/font-awesome-4.7/fonts/fontawesome-webfont.svg" />
        <File name="fontawesome-webfont" src="html/vendor/font-awesome-4.7/fonts/fontawesome-webfont.ttf" />
        <File name="fontawesome-webfont" src="html/vendor/font-awesome-4.7/fonts/fontawesome-webfont.woff" />
        <File name="fontawesome-webfont" src="html/vendor/font-awesome-4.7/fonts/fontawesome-webfont.woff2" />
        <File name="jquery" src="html/vendor/jquery/jquery.js" />
        <File name="jquery.min" src="html/vendor/jquery/jquery.min.js" />
        <File name="material-design-iconic-font" src="html/vendor/mdi-font/css/material-design-iconic-font.css" />
        <File name="material-design-iconic-font.min" src="html/vendor/mdi-font/css/material-design-iconic-font.min.css" />
        <File name="Material-Design-Iconic-Font" src="html/vendor/mdi-font/fonts/Material-Design-Iconic-Font.eot" />
        <File name="Material-Design-Iconic-Font" src="html/vendor/mdi-font/fonts/Material-Design-Iconic-Font.svg" />
        <File name="Material-Design-Iconic-Font" src="html/vendor/mdi-font/fonts/Material-Design-Iconic-Font.ttf" />
        <File name="Material-Design-Iconic-Font" src="html/vendor/mdi-font/fonts/Material-Design-Iconic-Font.woff" />
        <File name="Material-Design-Iconic-Font" src="html/vendor/mdi-font/fonts/Material-Design-Iconic-Font.woff2" />
        <File name="select2.min" src="html/vendor/select2/select2.min.css" />
        <File name="select2.min" src="html/vendor/select2/select2.min.js" />
        <File name="users" src="html/users/users.xml" />
        <File name="user-info" src="html/js/user-info.js" />
        <File name="user-register" src="html/js/user-register.js" />
        <File name="user-info" src="html/user-info.html" />
        <File name="user-register" src="html/user-register.html" />
        <File name="Rimouski" src="html/font/Rimouski.css" />
        <File name="rimouski_sb-webfont" src="html/font/rimouski_sb-webfont.ttf" />
        <File name="rimouski_sb-webfont" src="html/font/rimouski_sb-webfont.woff" />
        <File name="rimouski_sb-webfont" src="html/font/rimouski_sb-webfont.woff2" />
        <File name="button-home" src="html/icons/menu/button-home.png" />
        <File name="button-poweroff" src="html/icons/menu/button-poweroff.png" />
        <File name="button-volume" src="html/icons/menu/button-volume.png" />
        <File name="a01d" src="html/icons/weather/a01d.png" />
        <File name="a01n" src="html/icons/weather/a01n.png" />
        <File name="a02d" src="html/icons/weather/a02d.png" />
        <File name="a02n" src="html/icons/weather/a02n.png" />
        <File name="a03d" src="html/icons/weather/a03d.png" />
        <File name="a03n" src="html/icons/weather/a03n.png" />
        <File name="a04d" src="html/icons/weather/a04d.png" />
        <File name="a04n" src="html/icons/weather/a04n.png" />
        <File name="a05d" src="html/icons/weather/a05d.png" />
        <File name="a05n" src="html/icons/weather/a05n.png" />
        <File name="a06d" src="html/icons/weather/a06d.png" />
        <File name="a06n" src="html/icons/weather/a06n.png" />
        <File name="c01d" src="html/icons/weather/c01d.png" />
        <File name="c01n" src="html/icons/weather/c01n.png" />
        <File name="c02d" src="html/icons/weather/c02d.png" />
        <File name="c02n" src="html/icons/weather/c02n.png" />
        <File name="c03d" src="html/icons/weather/c03d.png" />
        <File name="c03n" src="html/icons/weather/c03n.png" />
        <File name="c04d" src="html/icons/weather/c04d.png" />
        <File name="c04n" src="html/icons/weather/c04n.png" />
        <File name="d01d" src="html/icons/weather/d01d.png" />
        <File name="d01n" src="html/icons/weather/d01n.png" />
        <File name="d02d" src="html/icons/weather/d02d.png" />
        <File name="d02n" src="html/icons/weather/d02n.png" />
        <File name="d03d" src="html/icons/weather/d03d.png" />
        <File name="d03n" src="html/icons/weather/d03n.png" />
        <File name="f01d" src="html/icons/weather/f01d.png" />
        <File name="f01n" src="html/icons/weather/f01n.png" />
        <File name="r01d" src="html/icons/weather/r01d.png" />
        <File name="r01n" src="html/icons/weather/r01n.png" />
        <File name="r02d" src="html/icons/weather/r02d.png" />
        <File name="r02n" src="html/icons/weather/r02n.png" />
        <File name="r03d" src="html/icons/weather/r03d.png" />
        <File name="r03n" src="html/icons/weather/r03n.png" />
        <File name="r04d" src="html/icons/weather/r04d.png" />
        <File name="r04n" src="html/icons/weather/r04n.png" />
        <File name="r05d" src="html/icons/weather/r05d.png" />
        <File name="r06d" src="html/icons/weather/r06d.png" />
        <File name="r06n" src="html/icons/weather/r06n.png" />
        <File name="s01n" src="html/icons/weather/s01n.png" />
        <File name="s02d" src="html/icons/weather/s02d.png" />
        <File name="s02n" src="html/icons/weather/s02n.png" />
        <File name="s03d" src="html/icons/weather/s03d.png" />
        <File name="s03n" src="html/icons/weather/s03n.png" />
        <File name="s04d" src="html/icons/weather/s04d.png" />
        <File name="s04n" src="html/icons/weather/s04n.png" />
        <File name="s05d" src="html/icons/weather/s05d.png" />
        <File name="s05n" src="html/icons/weather/s05n.png" />
        <File name="s06d" src="html/icons/weather/s06d.png" />
        <File name="s06n" src="html/icons/weather/s06n.png" />
        <File name="t01d" src="html/icons/weather/t01d.png" />
        <File name="t01n" src="html/icons/weather/t01n.png" />
        <File name="t02d" src="html/icons/weather/t02d.png" />
        <File name="t02n" src="html/icons/weather/t02n.png" />
        <File name="t03d" src="html/icons/weather/t03d.png" />
        <File name="t03n" src="html/icons/weather/t03n.png" />
        <File name="t04d" src="html/icons/weather/t04d.png" />
        <File name="t04n" src="html/icons/weather/t04n.png" />
        <File name="t05d" src="html/icons/weather/t05d.png" />
        <File name="t05n" src="html/icons/weather/t05n.png" />
        <File name="u00d" src="html/icons/weather/u00d.png" />
        <File name="u00n" src="html/icons/weather/u00n.png" />
        <File name="background-clear" src="html/imagenes/common/background-clear.png" />
        <File name="button-logo" src="html/icons/menu/button-logo.png" />
        <File name="master" src="html/css/master.css" />
        <File name="button-back" src="html/icons/menu/button-back.png" />
        <File name="button-user-add" src="html/icons/menu/button-user-add.png" />
        <File name="button-user-edit" src="html/icons/menu/button-user-edit.png" />
        <File name="activity" src="html/icons/weather/feather/activity.svg" />
        <File name="airplay" src="html/icons/weather/feather/airplay.svg" />
        <File name="alert-circle" src="html/icons/weather/feather/alert-circle.svg" />
        <File name="alert-octagon" src="html/icons/weather/feather/alert-octagon.svg" />
        <File name="alert-triangle" src="html/icons/weather/feather/alert-triangle.svg" />
        <File name="align-center" src="html/icons/weather/feather/align-center.svg" />
        <File name="align-justify" src="html/icons/weather/feather/align-justify.svg" />
        <File name="align-left" src="html/icons/weather/feather/align-left.svg" />
        <File name="align-right" src="html/icons/weather/feather/align-right.svg" />
        <File name="anchor" src="html/icons/weather/feather/anchor.svg" />
        <File name="aperture" src="html/icons/weather/feather/aperture.svg" />
        <File name="archive" src="html/icons/weather/feather/archive.svg" />
        <File name="arrow-down-circle" src="html/icons/weather/feather/arrow-down-circle.svg" />
        <File name="arrow-down-left" src="html/icons/weather/feather/arrow-down-left.svg" />
        <File name="arrow-down-right" src="html/icons/weather/feather/arrow-down-right.svg" />
        <File name="arrow-down" src="html/icons/weather/feather/arrow-down.svg" />
        <File name="arrow-left-circle" src="html/icons/weather/feather/arrow-left-circle.svg" />
        <File name="arrow-left" src="html/icons/weather/feather/arrow-left.svg" />
        <File name="arrow-right-circle" src="html/icons/weather/feather/arrow-right-circle.svg" />
        <File name="arrow-right" src="html/icons/weather/feather/arrow-right.svg" />
        <File name="arrow-up-circle" src="html/icons/weather/feather/arrow-up-circle.svg" />
        <File name="arrow-up-left" src="html/icons/weather/feather/arrow-up-left.svg" />
        <File name="arrow-up-right" src="html/icons/weather/feather/arrow-up-right.svg" />
        <File name="arrow-up" src="html/icons/weather/feather/arrow-up.svg" />
        <File name="at-sign" src="html/icons/weather/feather/at-sign.svg" />
        <File name="award" src="html/icons/weather/feather/award.svg" />
        <File name="bar-chart-2" src="html/icons/weather/feather/bar-chart-2.svg" />
        <File name="bar-chart" src="html/icons/weather/feather/bar-chart.svg" />
        <File name="battery-charging" src="html/icons/weather/feather/battery-charging.svg" />
        <File name="battery" src="html/icons/weather/feather/battery.svg" />
        <File name="bell-off" src="html/icons/weather/feather/bell-off.svg" />
        <File name="bell" src="html/icons/weather/feather/bell.svg" />
        <File name="bluetooth" src="html/icons/weather/feather/bluetooth.svg" />
        <File name="bold" src="html/icons/weather/feather/bold.svg" />
        <File name="book-open" src="html/icons/weather/feather/book-open.svg" />
        <File name="book" src="html/icons/weather/feather/book.svg" />
        <File name="bookmark" src="html/icons/weather/feather/bookmark.svg" />
        <File name="box" src="html/icons/weather/feather/box.svg" />
        <File name="briefcase" src="html/icons/weather/feather/briefcase.svg" />
        <File name="calendar" src="html/icons/weather/feather/calendar.svg" />
        <File name="camera-off" src="html/icons/weather/feather/camera-off.svg" />
        <File name="camera" src="html/icons/weather/feather/camera.svg" />
        <File name="cast" src="html/icons/weather/feather/cast.svg" />
        <File name="check-circle" src="html/icons/weather/feather/check-circle.svg" />
        <File name="check-square" src="html/icons/weather/feather/check-square.svg" />
        <File name="check" src="html/icons/weather/feather/check.svg" />
        <File name="chevron-down" src="html/icons/weather/feather/chevron-down.svg" />
        <File name="chevron-left" src="html/icons/weather/feather/chevron-left.svg" />
        <File name="chevron-right" src="html/icons/weather/feather/chevron-right.svg" />
        <File name="chevron-up" src="html/icons/weather/feather/chevron-up.svg" />
        <File name="chevrons-down" src="html/icons/weather/feather/chevrons-down.svg" />
        <File name="chevrons-left" src="html/icons/weather/feather/chevrons-left.svg" />
        <File name="chevrons-right" src="html/icons/weather/feather/chevrons-right.svg" />
        <File name="chevrons-up" src="html/icons/weather/feather/chevrons-up.svg" />
        <File name="chrome" src="html/icons/weather/feather/chrome.svg" />
        <File name="circle" src="html/icons/weather/feather/circle.svg" />
        <File name="clipboard" src="html/icons/weather/feather/clipboard.svg" />
        <File name="clock" src="html/icons/weather/feather/clock.svg" />
        <File name="cloud-drizzle" src="html/icons/weather/feather/cloud-drizzle.svg" />
        <File name="cloud-lightning" src="html/icons/weather/feather/cloud-lightning.svg" />
        <File name="cloud-off" src="html/icons/weather/feather/cloud-off.svg" />
        <File name="cloud-rain" src="html/icons/weather/feather/cloud-rain.svg" />
        <File name="cloud-snow" src="html/icons/weather/feather/cloud-snow.svg" />
        <File name="cloud" src="html/icons/weather/feather/cloud.svg" />
        <File name="code" src="html/icons/weather/feather/code.svg" />
        <File name="codepen" src="html/icons/weather/feather/codepen.svg" />
        <File name="codesandbox" src="html/icons/weather/feather/codesandbox.svg" />
        <File name="coffee" src="html/icons/weather/feather/coffee.svg" />
        <File name="columns" src="html/icons/weather/feather/columns.svg" />
        <File name="command" src="html/icons/weather/feather/command.svg" />
        <File name="compass" src="html/icons/weather/feather/compass.svg" />
        <File name="copy" src="html/icons/weather/feather/copy.svg" />
        <File name="corner-down-left" src="html/icons/weather/feather/corner-down-left.svg" />
        <File name="corner-down-right" src="html/icons/weather/feather/corner-down-right.svg" />
        <File name="corner-left-down" src="html/icons/weather/feather/corner-left-down.svg" />
        <File name="corner-left-up" src="html/icons/weather/feather/corner-left-up.svg" />
        <File name="corner-right-down" src="html/icons/weather/feather/corner-right-down.svg" />
        <File name="corner-right-up" src="html/icons/weather/feather/corner-right-up.svg" />
        <File name="corner-up-left" src="html/icons/weather/feather/corner-up-left.svg" />
        <File name="corner-up-right" src="html/icons/weather/feather/corner-up-right.svg" />
        <File name="cpu" src="html/icons/weather/feather/cpu.svg" />
        <File name="credit-card" src="html/icons/weather/feather/credit-card.svg" />
        <File name="crop" src="html/icons/weather/feather/crop.svg" />
        <File name="crosshair" src="html/icons/weather/feather/crosshair.svg" />
        <File name="database" src="html/icons/weather/feather/database.svg" />
        <File name="delete" src="html/icons/weather/feather/delete.svg" />
        <File name="disc" src="html/icons/weather/feather/disc.svg" />
        <File name="divide-circle" src="html/icons/weather/feather/divide-circle.svg" />
        <File name="divide-square" src="html/icons/weather/feather/divide-square.svg" />
        <File name="divide" src="html/icons/weather/feather/divide.svg" />
        <File name="dollar-sign" src="html/icons/weather/feather/dollar-sign.svg" />
        <File name="download-cloud" src="html/icons/weather/feather/download-cloud.svg" />
        <File name="download" src="html/icons/weather/feather/download.svg" />
        <File name="dribbble" src="html/icons/weather/feather/dribbble.svg" />
        <File name="droplet" src="html/icons/weather/feather/droplet.svg" />
        <File name="edit-2" src="html/icons/weather/feather/edit-2.svg" />
        <File name="edit-3" src="html/icons/weather/feather/edit-3.svg" />
        <File name="edit" src="html/icons/weather/feather/edit.svg" />
        <File name="external-link" src="html/icons/weather/feather/external-link.svg" />
        <File name="eye-off" src="html/icons/weather/feather/eye-off.svg" />
        <File name="eye" src="html/icons/weather/feather/eye.svg" />
        <File name="facebook" src="html/icons/weather/feather/facebook.svg" />
        <File name="fast-forward" src="html/icons/weather/feather/fast-forward.svg" />
        <File name="feather" src="html/icons/weather/feather/feather.svg" />
        <File name="figma" src="html/icons/weather/feather/figma.svg" />
        <File name="file-minus" src="html/icons/weather/feather/file-minus.svg" />
        <File name="file-plus" src="html/icons/weather/feather/file-plus.svg" />
        <File name="file-text" src="html/icons/weather/feather/file-text.svg" />
        <File name="file" src="html/icons/weather/feather/file.svg" />
        <File name="film" src="html/icons/weather/feather/film.svg" />
        <File name="filter" src="html/icons/weather/feather/filter.svg" />
        <File name="flag" src="html/icons/weather/feather/flag.svg" />
        <File name="folder-minus" src="html/icons/weather/feather/folder-minus.svg" />
        <File name="folder-plus" src="html/icons/weather/feather/folder-plus.svg" />
        <File name="folder" src="html/icons/weather/feather/folder.svg" />
        <File name="framer" src="html/icons/weather/feather/framer.svg" />
        <File name="frown" src="html/icons/weather/feather/frown.svg" />
        <File name="gift" src="html/icons/weather/feather/gift.svg" />
        <File name="git-branch" src="html/icons/weather/feather/git-branch.svg" />
        <File name="git-commit" src="html/icons/weather/feather/git-commit.svg" />
        <File name="git-merge" src="html/icons/weather/feather/git-merge.svg" />
        <File name="git-pull-request" src="html/icons/weather/feather/git-pull-request.svg" />
        <File name="github" src="html/icons/weather/feather/github.svg" />
        <File name="gitlab" src="html/icons/weather/feather/gitlab.svg" />
        <File name="globe" src="html/icons/weather/feather/globe.svg" />
        <File name="grid" src="html/icons/weather/feather/grid.svg" />
        <File name="hard-drive" src="html/icons/weather/feather/hard-drive.svg" />
        <File name="hash" src="html/icons/weather/feather/hash.svg" />
        <File name="headphones" src="html/icons/weather/feather/headphones.svg" />
        <File name="heart" src="html/icons/weather/feather/heart.svg" />
        <File name="help-circle" src="html/icons/weather/feather/help-circle.svg" />
        <File name="hexagon" src="html/icons/weather/feather/hexagon.svg" />
        <File name="home" src="html/icons/weather/feather/home.svg" />
        <File name="image" src="html/icons/weather/feather/image.svg" />
        <File name="inbox" src="html/icons/weather/feather/inbox.svg" />
        <File name="info" src="html/icons/weather/feather/info.svg" />
        <File name="instagram" src="html/icons/weather/feather/instagram.svg" />
        <File name="italic" src="html/icons/weather/feather/italic.svg" />
        <File name="key" src="html/icons/weather/feather/key.svg" />
        <File name="layers" src="html/icons/weather/feather/layers.svg" />
        <File name="layout" src="html/icons/weather/feather/layout.svg" />
        <File name="life-buoy" src="html/icons/weather/feather/life-buoy.svg" />
        <File name="link-2" src="html/icons/weather/feather/link-2.svg" />
        <File name="link" src="html/icons/weather/feather/link.svg" />
        <File name="linkedin" src="html/icons/weather/feather/linkedin.svg" />
        <File name="list" src="html/icons/weather/feather/list.svg" />
        <File name="loader" src="html/icons/weather/feather/loader.svg" />
        <File name="lock" src="html/icons/weather/feather/lock.svg" />
        <File name="log-in" src="html/icons/weather/feather/log-in.svg" />
        <File name="log-out" src="html/icons/weather/feather/log-out.svg" />
        <File name="mail" src="html/icons/weather/feather/mail.svg" />
        <File name="map-pin-white" src="html/icons/weather/feather/map-pin-white.png" />
        <File name="map-pin" src="html/icons/weather/feather/map-pin.svg" />
        <File name="map" src="html/icons/weather/feather/map.svg" />
        <File name="maximize-2" src="html/icons/weather/feather/maximize-2.svg" />
        <File name="maximize" src="html/icons/weather/feather/maximize.svg" />
        <File name="meh" src="html/icons/weather/feather/meh.svg" />
        <File name="menu" src="html/icons/weather/feather/menu.svg" />
        <File name="message-circle" src="html/icons/weather/feather/message-circle.svg" />
        <File name="message-square" src="html/icons/weather/feather/message-square.svg" />
        <File name="mic-off" src="html/icons/weather/feather/mic-off.svg" />
        <File name="mic" src="html/icons/weather/feather/mic.svg" />
        <File name="minimize-2" src="html/icons/weather/feather/minimize-2.svg" />
        <File name="minimize" src="html/icons/weather/feather/minimize.svg" />
        <File name="minus-circle" src="html/icons/weather/feather/minus-circle.svg" />
        <File name="minus-square" src="html/icons/weather/feather/minus-square.svg" />
        <File name="minus" src="html/icons/weather/feather/minus.svg" />
        <File name="monitor" src="html/icons/weather/feather/monitor.svg" />
        <File name="moon" src="html/icons/weather/feather/moon.svg" />
        <File name="more-horizontal" src="html/icons/weather/feather/more-horizontal.svg" />
        <File name="more-vertical" src="html/icons/weather/feather/more-vertical.svg" />
        <File name="mouse-pointer" src="html/icons/weather/feather/mouse-pointer.svg" />
        <File name="move" src="html/icons/weather/feather/move.svg" />
        <File name="music" src="html/icons/weather/feather/music.svg" />
        <File name="navigation-2" src="html/icons/weather/feather/navigation-2.svg" />
        <File name="navigation" src="html/icons/weather/feather/navigation.svg" />
        <File name="octagon" src="html/icons/weather/feather/octagon.svg" />
        <File name="package" src="html/icons/weather/feather/package.svg" />
        <File name="paperclip" src="html/icons/weather/feather/paperclip.svg" />
        <File name="pause-circle" src="html/icons/weather/feather/pause-circle.svg" />
        <File name="pause" src="html/icons/weather/feather/pause.svg" />
        <File name="pen-tool" src="html/icons/weather/feather/pen-tool.svg" />
        <File name="percent" src="html/icons/weather/feather/percent.svg" />
        <File name="phone-call" src="html/icons/weather/feather/phone-call.svg" />
        <File name="phone-forwarded" src="html/icons/weather/feather/phone-forwarded.svg" />
        <File name="phone-incoming" src="html/icons/weather/feather/phone-incoming.svg" />
        <File name="phone-missed" src="html/icons/weather/feather/phone-missed.svg" />
        <File name="phone-off" src="html/icons/weather/feather/phone-off.svg" />
        <File name="phone-outgoing" src="html/icons/weather/feather/phone-outgoing.svg" />
        <File name="phone" src="html/icons/weather/feather/phone.svg" />
        <File name="pie-chart" src="html/icons/weather/feather/pie-chart.svg" />
        <File name="play-circle" src="html/icons/weather/feather/play-circle.svg" />
        <File name="play" src="html/icons/weather/feather/play.svg" />
        <File name="plus-circle" src="html/icons/weather/feather/plus-circle.svg" />
        <File name="plus-square" src="html/icons/weather/feather/plus-square.svg" />
        <File name="plus" src="html/icons/weather/feather/plus.svg" />
        <File name="pocket" src="html/icons/weather/feather/pocket.svg" />
        <File name="power" src="html/icons/weather/feather/power.svg" />
        <File name="printer" src="html/icons/weather/feather/printer.svg" />
        <File name="radio" src="html/icons/weather/feather/radio.svg" />
        <File name="refresh-ccw" src="html/icons/weather/feather/refresh-ccw.svg" />
        <File name="refresh-cw" src="html/icons/weather/feather/refresh-cw.svg" />
        <File name="repeat" src="html/icons/weather/feather/repeat.svg" />
        <File name="rewind" src="html/icons/weather/feather/rewind.svg" />
        <File name="rotate-ccw" src="html/icons/weather/feather/rotate-ccw.svg" />
        <File name="rotate-cw" src="html/icons/weather/feather/rotate-cw.svg" />
        <File name="rss" src="html/icons/weather/feather/rss.svg" />
        <File name="save" src="html/icons/weather/feather/save.svg" />
        <File name="scissors" src="html/icons/weather/feather/scissors.svg" />
        <File name="search" src="html/icons/weather/feather/search.svg" />
        <File name="send" src="html/icons/weather/feather/send.svg" />
        <File name="server" src="html/icons/weather/feather/server.svg" />
        <File name="settings" src="html/icons/weather/feather/settings.svg" />
        <File name="share-2" src="html/icons/weather/feather/share-2.svg" />
        <File name="share" src="html/icons/weather/feather/share.svg" />
        <File name="shield-off" src="html/icons/weather/feather/shield-off.svg" />
        <File name="shield" src="html/icons/weather/feather/shield.svg" />
        <File name="shopping-bag" src="html/icons/weather/feather/shopping-bag.svg" />
        <File name="shopping-cart" src="html/icons/weather/feather/shopping-cart.svg" />
        <File name="shuffle" src="html/icons/weather/feather/shuffle.svg" />
        <File name="sidebar" src="html/icons/weather/feather/sidebar.svg" />
        <File name="skip-back" src="html/icons/weather/feather/skip-back.svg" />
        <File name="skip-forward" src="html/icons/weather/feather/skip-forward.svg" />
        <File name="slack" src="html/icons/weather/feather/slack.svg" />
        <File name="slash" src="html/icons/weather/feather/slash.svg" />
        <File name="sliders" src="html/icons/weather/feather/sliders.svg" />
        <File name="smartphone" src="html/icons/weather/feather/smartphone.svg" />
        <File name="smile" src="html/icons/weather/feather/smile.svg" />
        <File name="speaker" src="html/icons/weather/feather/speaker.svg" />
        <File name="square" src="html/icons/weather/feather/square.svg" />
        <File name="star" src="html/icons/weather/feather/star.svg" />
        <File name="stop-circle" src="html/icons/weather/feather/stop-circle.svg" />
        <File name="sun" src="html/icons/weather/feather/sun.svg" />
        <File name="sunrise" src="html/icons/weather/feather/sunrise.svg" />
        <File name="sunset" src="html/icons/weather/feather/sunset.svg" />
        <File name="tablet" src="html/icons/weather/feather/tablet.svg" />
        <File name="tag" src="html/icons/weather/feather/tag.svg" />
        <File name="target" src="html/icons/weather/feather/target.svg" />
        <File name="terminal" src="html/icons/weather/feather/terminal.svg" />
        <File name="thermometer" src="html/icons/weather/feather/thermometer.svg" />
        <File name="thumbs-down" src="html/icons/weather/feather/thumbs-down.svg" />
        <File name="thumbs-up" src="html/icons/weather/feather/thumbs-up.svg" />
        <File name="toggle-left" src="html/icons/weather/feather/toggle-left.svg" />
        <File name="toggle-right" src="html/icons/weather/feather/toggle-right.svg" />
        <File name="tool" src="html/icons/weather/feather/tool.svg" />
        <File name="trash-2" src="html/icons/weather/feather/trash-2.svg" />
        <File name="trash" src="html/icons/weather/feather/trash.svg" />
        <File name="trello" src="html/icons/weather/feather/trello.svg" />
        <File name="trending-down" src="html/icons/weather/feather/trending-down.svg" />
        <File name="trending-up" src="html/icons/weather/feather/trending-up.svg" />
        <File name="triangle" src="html/icons/weather/feather/triangle.svg" />
        <File name="truck" src="html/icons/weather/feather/truck.svg" />
        <File name="tv" src="html/icons/weather/feather/tv.svg" />
        <File name="twitch" src="html/icons/weather/feather/twitch.svg" />
        <File name="twitter" src="html/icons/weather/feather/twitter.svg" />
        <File name="type" src="html/icons/weather/feather/type.svg" />
        <File name="umbrella" src="html/icons/weather/feather/umbrella.svg" />
        <File name="underline" src="html/icons/weather/feather/underline.svg" />
        <File name="unlock" src="html/icons/weather/feather/unlock.svg" />
        <File name="upload-cloud" src="html/icons/weather/feather/upload-cloud.svg" />
        <File name="upload" src="html/icons/weather/feather/upload.svg" />
        <File name="user-check" src="html/icons/weather/feather/user-check.svg" />
        <File name="user-minus" src="html/icons/weather/feather/user-minus.svg" />
        <File name="user-plus" src="html/icons/weather/feather/user-plus.svg" />
        <File name="user-x" src="html/icons/weather/feather/user-x.svg" />
        <File name="user" src="html/icons/weather/feather/user.svg" />
        <File name="users" src="html/icons/weather/feather/users.svg" />
        <File name="video-off" src="html/icons/weather/feather/video-off.svg" />
        <File name="video" src="html/icons/weather/feather/video.svg" />
        <File name="voicemail" src="html/icons/weather/feather/voicemail.svg" />
        <File name="volume-1" src="html/icons/weather/feather/volume-1.svg" />
        <File name="volume-2" src="html/icons/weather/feather/volume-2.svg" />
        <File name="volume-x" src="html/icons/weather/feather/volume-x.svg" />
        <File name="volume" src="html/icons/weather/feather/volume.svg" />
        <File name="watch" src="html/icons/weather/feather/watch.svg" />
        <File name="wifi-off" src="html/icons/weather/feather/wifi-off.svg" />
        <File name="wifi" src="html/icons/weather/feather/wifi.svg" />
        <File name="wind" src="html/icons/weather/feather/wind.svg" />
        <File name="x-circle" src="html/icons/weather/feather/x-circle.svg" />
        <File name="x-octagon" src="html/icons/weather/feather/x-octagon.svg" />
        <File name="x-square" src="html/icons/weather/feather/x-square.svg" />
        <File name="x" src="html/icons/weather/feather/x.svg" />
        <File name="youtube" src="html/icons/weather/feather/youtube.svg" />
        <File name="zap-off" src="html/icons/weather/feather/zap-off.svg" />
        <File name="zap" src="html/icons/weather/feather/zap.svg" />
        <File name="zoom-in" src="html/icons/weather/feather/zoom-in.svg" />
        <File name="zoom-out" src="html/icons/weather/feather/zoom-out.svg" />
        <File name="feather" src="html/icons/weather/feather/feather.zip" />
        <File name="a01d" src="html/icons/weather/old/a01d.png" />
        <File name="a01n" src="html/icons/weather/old/a01n.png" />
        <File name="a02d" src="html/icons/weather/old/a02d.png" />
        <File name="a02n" src="html/icons/weather/old/a02n.png" />
        <File name="a03d" src="html/icons/weather/old/a03d.png" />
        <File name="a03n" src="html/icons/weather/old/a03n.png" />
        <File name="a04d" src="html/icons/weather/old/a04d.png" />
        <File name="a04n" src="html/icons/weather/old/a04n.png" />
        <File name="a05d" src="html/icons/weather/old/a05d.png" />
        <File name="a05n" src="html/icons/weather/old/a05n.png" />
        <File name="a06d" src="html/icons/weather/old/a06d.png" />
        <File name="a06n" src="html/icons/weather/old/a06n.png" />
        <File name="c01d" src="html/icons/weather/old/c01d.png" />
        <File name="c01n" src="html/icons/weather/old/c01n.png" />
        <File name="c02d" src="html/icons/weather/old/c02d.png" />
        <File name="c02n" src="html/icons/weather/old/c02n.png" />
        <File name="c03d" src="html/icons/weather/old/c03d.png" />
        <File name="c03n" src="html/icons/weather/old/c03n.png" />
        <File name="c04d" src="html/icons/weather/old/c04d.png" />
        <File name="c04n" src="html/icons/weather/old/c04n.png" />
        <File name="d01d" src="html/icons/weather/old/d01d.png" />
        <File name="d01n" src="html/icons/weather/old/d01n.png" />
        <File name="d02d" src="html/icons/weather/old/d02d.png" />
        <File name="d02n" src="html/icons/weather/old/d02n.png" />
        <File name="d03d" src="html/icons/weather/old/d03d.png" />
        <File name="d03n" src="html/icons/weather/old/d03n.png" />
        <File name="f01d" src="html/icons/weather/old/f01d.png" />
        <File name="f01n" src="html/icons/weather/old/f01n.png" />
        <File name="r01d" src="html/icons/weather/old/r01d.png" />
        <File name="r01n" src="html/icons/weather/old/r01n.png" />
        <File name="r02d" src="html/icons/weather/old/r02d.png" />
        <File name="r02n" src="html/icons/weather/old/r02n.png" />
        <File name="r03d" src="html/icons/weather/old/r03d.png" />
        <File name="r03n" src="html/icons/weather/old/r03n.png" />
        <File name="r04d" src="html/icons/weather/old/r04d.png" />
        <File name="r04n" src="html/icons/weather/old/r04n.png" />
        <File name="r05d" src="html/icons/weather/old/r05d.png" />
        <File name="r05n" src="html/icons/weather/old/r05n.png" />
        <File name="r06d" src="html/icons/weather/old/r06d.png" />
        <File name="r06n" src="html/icons/weather/old/r06n.png" />
        <File name="s01d" src="html/icons/weather/old/s01d.png" />
        <File name="s01n" src="html/icons/weather/old/s01n.png" />
        <File name="s02d" src="html/icons/weather/old/s02d.png" />
        <File name="s02n" src="html/icons/weather/old/s02n.png" />
        <File name="s03d" src="html/icons/weather/old/s03d.png" />
        <File name="s03n" src="html/icons/weather/old/s03n.png" />
        <File name="s04d" src="html/icons/weather/old/s04d.png" />
        <File name="s04n" src="html/icons/weather/old/s04n.png" />
        <File name="s05d" src="html/icons/weather/old/s05d.png" />
        <File name="s05n" src="html/icons/weather/old/s05n.png" />
        <File name="s06d" src="html/icons/weather/old/s06d.png" />
        <File name="s06n" src="html/icons/weather/old/s06n.png" />
        <File name="t01d" src="html/icons/weather/old/t01d.png" />
        <File name="t01n" src="html/icons/weather/old/t01n.png" />
        <File name="t02d" src="html/icons/weather/old/t02d.png" />
        <File name="t02n" src="html/icons/weather/old/t02n.png" />
        <File name="t03d" src="html/icons/weather/old/t03d.png" />
        <File name="t03n" src="html/icons/weather/old/t03n.png" />
        <File name="t04d" src="html/icons/weather/old/t04d.png" />
        <File name="t04n" src="html/icons/weather/old/t04n.png" />
        <File name="t05d" src="html/icons/weather/old/t05d.png" />
        <File name="t05n" src="html/icons/weather/old/t05n.png" />
        <File name="u00d" src="html/icons/weather/old/u00d.png" />
        <File name="u00n" src="html/icons/weather/old/u00n.png" />
        <File name="a01d" src="html/icons/weather/original/a01d.png" />
        <File name="a01n" src="html/icons/weather/original/a01n.png" />
        <File name="a02d" src="html/icons/weather/original/a02d.png" />
        <File name="a02n" src="html/icons/weather/original/a02n.png" />
        <File name="a03d" src="html/icons/weather/original/a03d.png" />
        <File name="a03n" src="html/icons/weather/original/a03n.png" />
        <File name="a04d" src="html/icons/weather/original/a04d.png" />
        <File name="a04n" src="html/icons/weather/original/a04n.png" />
        <File name="a05d" src="html/icons/weather/original/a05d.png" />
        <File name="a05n" src="html/icons/weather/original/a05n.png" />
        <File name="a06d" src="html/icons/weather/original/a06d.png" />
        <File name="a06n" src="html/icons/weather/original/a06n.png" />
        <File name="c01d" src="html/icons/weather/original/c01d.png" />
        <File name="c01n" src="html/icons/weather/original/c01n.png" />
        <File name="c02d" src="html/icons/weather/original/c02d.png" />
        <File name="c02n" src="html/icons/weather/original/c02n.png" />
        <File name="c03d" src="html/icons/weather/original/c03d.png" />
        <File name="c03n" src="html/icons/weather/original/c03n.png" />
        <File name="c04d" src="html/icons/weather/original/c04d.png" />
        <File name="c04n" src="html/icons/weather/original/c04n.png" />
        <File name="d01d" src="html/icons/weather/original/d01d.png" />
        <File name="d01n" src="html/icons/weather/original/d01n.png" />
        <File name="d02d" src="html/icons/weather/original/d02d.png" />
        <File name="d02n" src="html/icons/weather/original/d02n.png" />
        <File name="d03d" src="html/icons/weather/original/d03d.png" />
        <File name="d03n" src="html/icons/weather/original/d03n.png" />
        <File name="f01d" src="html/icons/weather/original/f01d.png" />
        <File name="f01n" src="html/icons/weather/original/f01n.png" />
        <File name="r01d" src="html/icons/weather/original/r01d.png" />
        <File name="r01n" src="html/icons/weather/original/r01n.png" />
        <File name="r02d" src="html/icons/weather/original/r02d.png" />
        <File name="r02n" src="html/icons/weather/original/r02n.png" />
        <File name="r03d" src="html/icons/weather/original/r03d.png" />
        <File name="r03n" src="html/icons/weather/original/r03n.png" />
        <File name="r04d" src="html/icons/weather/original/r04d.png" />
        <File name="r04n" src="html/icons/weather/original/r04n.png" />
        <File name="r05d" src="html/icons/weather/original/r05d.png" />
        <File name="r05n-" src="html/icons/weather/original/r05n-.png" />
        <File name="r06d" src="html/icons/weather/original/r06d.png" />
        <File name="r06n" src="html/icons/weather/original/r06n.png" />
        <File name="s01n" src="html/icons/weather/original/s01n.png" />
        <File name="s02d" src="html/icons/weather/original/s02d.png" />
        <File name="s02n" src="html/icons/weather/original/s02n.png" />
        <File name="s03d" src="html/icons/weather/original/s03d.png" />
        <File name="s03n" src="html/icons/weather/original/s03n.png" />
        <File name="s04d" src="html/icons/weather/original/s04d.png" />
        <File name="s04n" src="html/icons/weather/original/s04n.png" />
        <File name="s05d" src="html/icons/weather/original/s05d.png" />
        <File name="s05n" src="html/icons/weather/original/s05n.png" />
        <File name="s06d" src="html/icons/weather/original/s06d.png" />
        <File name="s06n" src="html/icons/weather/original/s06n.png" />
        <File name="t01d" src="html/icons/weather/original/t01d.png" />
        <File name="t01n" src="html/icons/weather/original/t01n.png" />
        <File name="t02d" src="html/icons/weather/original/t02d.png" />
        <File name="t02n" src="html/icons/weather/original/t02n.png" />
        <File name="t03d" src="html/icons/weather/original/t03d.png" />
        <File name="t03n" src="html/icons/weather/original/t03n.png" />
        <File name="t04d" src="html/icons/weather/original/t04d.png" />
        <File name="t04n" src="html/icons/weather/original/t04n.png" />
        <File name="t05d" src="html/icons/weather/original/t05d.png" />
        <File name="t05n" src="html/icons/weather/original/t05n.png" />
        <File name="u00d" src="html/icons/weather/original/u00d.png" />
        <File name="u00n" src="html/icons/weather/original/u00n.png" />
        <File name="r05n" src="html/icons/weather/r05n.png" />
        <File name="s01d" src="html/icons/weather/s01d.png" />
        <File name="search" src="html/icons/menu/search.png" />
        <File name="button-train" src="html/icons/menu/button-train.png" />
        <File name="activities" src="html/users/activities.xml" />
        <File name="button-logo-rsait-w" src="html/icons/menu/button-logo-rsait-w.png" />
        <File name="index" src="html/css/index.css" />
        <File name="button-logo-urola" src="html/icons/menu/button-logo-urola.png" />
        <File name="website-g" src="html/imagenes/index/website-g.png" />
        <File name="website" src="html/imagenes/index/website.png" />
        <File name="preguntas" src="html/css/preguntas.css" />
        <File name="resultados" src="html/css/resultados.css" />
        <File name="general_knowledge" src="html/db/games/preguntas/general_knowledge.js" />
        <File name="science_and_nature" src="html/db/games/preguntas/science_and_nature.js" />
        <File name="sports" src="html/db/games/preguntas/sports.js" />
        <File name="alertify.min" src="html/vendor/alertify.min.js" />
        <File name="jquery-3.3.1.min" src="html/vendor/jquery-3.3.1.min.js" />
        <File name="js.cookie-2.2.1.min" src="html/vendor/js.cookie-2.2.1.min.js" />
        <File name="valences" src="html/users/valences.xml" />
        <File name="general_knowledge" src="html/db/games/preguntas/es/general_knowledge.js" />
        <File name="science_and_nature" src="html/db/games/preguntas/es/science_and_nature.js" />
        <File name="sports" src="html/db/games/preguntas/es/sports.js" />
        <File name="user-login" src="html/css/user-login.css" />
        <File name="button-exit" src="html/icons/menu/button-exit.png" />
        <File name="users_with_content" src="html/users/users_with_content.xml" />
        <File name="activities_with_content" src="html/users/activities_with_content" />
        <File name="c_cpp_properties" src="html/.vscode/c_cpp_properties.json" />
        <File name="settings" src="html/.vscode/settings.json" />
        <File name="proba" src="html/users/proba.py" />
        <File name="button-user-login" src="html/icons/menu/button-user-login.png" />
        <File name="index_orig" src="html/index_orig.html" />
        <File name="empty_document.old" src="html/users/profiles/empty_document.old.txt" />
        <File name="preguntas" src="html/js/preguntas.js" />
        <File name="preguntas" src="html/preguntas.html" />
        <File name="stopWatch" src="html/js/stopWatch.js" />
        <File name="tiempo" src="html/js/tiempo.js" />
        <File name="juegos-master" src="html/css/juegos-master.css" />
        <File name="cuadrados-color" src="html/imagenes/juegos-general/cuadrados-color.png" />
        <File name="cuadrados-grey" src="html/imagenes/juegos-general/cuadrados-grey.png" />
        <File name="emotion-happy-color" src="html/imagenes/juegos-general/emotion-happy-color.png" />
        <File name="emotion-happy" src="html/imagenes/juegos-general/emotion-happy.png" />
        <File name="emotion-neutral-color" src="html/imagenes/juegos-general/emotion-neutral-color.png" />
        <File name="emotion-neutral" src="html/imagenes/juegos-general/emotion-neutral.png" />
        <File name="emotion-sad-color" src="html/imagenes/juegos-general/emotion-sad-color.png" />
        <File name="emotion-sad" src="html/imagenes/juegos-general/emotion-sad.png" />
        <File name="reloj-blue" src="html/imagenes/juegos-general/reloj-blue.png" />
        <File name="trofeo-resultados-white" src="html/imagenes/juegos-general/trofeo-resultados-white.png" />
        <File name="trofeo-resultados-yellow" src="html/imagenes/juegos-general/trofeo-resultados-yellow.png" />
        <File name="crown-blue" src="html/imagenes/preguntas/crown-blue.png" />
        <File name="green-tick" src="html/imagenes/preguntas/green-tick.png" />
        <File name="13" src="html/imagenes/preguntas/imgPreguntas/13.png" />
        <File name="18" src="html/imagenes/preguntas/imgPreguntas/18.png" />
        <File name="32" src="html/imagenes/preguntas/imgPreguntas/32.png" />
        <File name="44" src="html/imagenes/preguntas/imgPreguntas/44.png" />
        <File name="luna" src="html/imagenes/preguntas/imgPreguntas/luna.jpg" />
        <File name="preguntas" src="html/imagenes/preguntas/preguntas.gif" />
        <File name="preguntas" src="html/imagenes/preguntas/preguntas.mp4" />
        <File name="quiz-background" src="html/imagenes/preguntas/quiz-background.png" />
        <File name="red-cross" src="html/imagenes/preguntas/red-cross.png" />
    </Resources>
    <Topics />
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
        <Translation name="translation_es_ES" src="translations/translation_es_ES.ts" language="es_ES" />
    </Translations>
</Package>
